import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              window.difyChatbotConfig = {
                token: '9qP8PAWo0qFbRXO5'
              }
            `,
          }}
        />
        <script
          src="https://udify.app/embed.min.js"
          id="9qP8PAWo0qFbRXO5"
          defer
        ></script>
        <style>
          {`
            #dify-chatbot-bubble-button {
              background-color: #1C64F2 !important;
            }
          `}
        </style>
      </head>
      <body className={inter.className}>
        {children}
        <a href="https://udify.app/chat/9qP8PAWo0qFbRXO5" target="_blank" rel="noopener noreferrer">
          <button>今すぐ体験する</button>
        </a>
        <a href="https://udify.app/chat/9qP8PAWo0qFbRXO5" target="_blank" rel="noopener noreferrer">
          <button>チャットを開始</button>
        </a>
      </body>
    </html>
  );
}